// Code generated by MockGen. DO NOT EDIT.
// Source: numerator_service.go
//
// Generated by this command:
//
//	mockgen -source numerator_service.go -destination ./mock_service/mock_numerator_service/numerator_service_gen.go
//

// Package mock_service is a generated GoMock package.
package mock_service
